shallow_clone: false

os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  VCVAR2017: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'

  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

install:
  - git submodule update --init --recursive
  - ps: |
      if (-not (Test-Path $env:PYTHON)) {
        curl -o install_python.ps1 https://raw.githubusercontent.com/matthew-brett/multibuild/devel/install_python.ps1
        .\install_python.ps1
      }
  - ps: if (-not (Test-Path $env:PYTHON)) { throw "No $env:PYTHON" }
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version

build_script:
  # Build the compiled extension
  - call "%VCVAR2017%" x86_amd64
  - cmd: |
      "%PYTHON%\\python.exe" -m pip install --upgrade pip
      "%PYTHON%\\python.exe" -m pip install --upgrade setuptools
      set "CI_BUILD=1" && "%PYTHON%\\python.exe" -m pip wheel --wheel-dir=%cd%\dist . --verbose

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\bgfx_python*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#