languages:
  - cpp
  - python

sudo: false

git:
  quiet: true
  depth: false
  submodules: true

matrix:
  include:
    - compiler: gcc
      os: linux
      python: 3.7
      dist: xenial
      env: CC=gcc-8 CXX=g++-8
      before_install: pyenv global 3.7

    - compiler: clang
      os: osx
      env: CC=gcc CXX=g++
      osx_image: xcode10.2
      language: shell
      before_install: python3 --version ; pip3 --version ; sw_vers

    - os: windows
      language: shell
      before_install:
        - choco install python visualstudio2017-workload-vctools -y
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH Platform=x64 Configuration=Release CC=cl.exe CXX=cl.exe

  allow_failures:
    - os: windows

addons:
  homebrew:
    update: true
    packages:
    - cmake
    - ninja
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang
    - cmake
    - ninja
    - mesa-common-dev

install:
  - pip3 install --user -U pip setuptools wheel
  - pip3 install --user scikit-build cmake ninja

script:
  - python3 setup.py sdist bdist_wheel || python setup.py sdist bdist_wheel

#branches:
#  only:
#    - master

notifications:
  email: false