language: python
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8

git:
  quiet: true
  depth: false
  submodules: true

jobs:
  include:
    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: skip
      script: python3 setup.py sdist --formats=gztar
#      after_success: |
#        python3 -m pip install twine
#        python3 -m twine upload --skip-existing dist/*.tar.gz

    - stage: deploy
      name: "Build and deploy Linux wheels"
      os: linux
      services: docker
      install: python3 -m pip install cibuildwheel==1.3.0
      script: python3 -m cibuildwheel --output-dir wheelhouse
      after_success: bash -x -e .travis/after_success.sh

    - stage: deploy
      name: "Build and deploy macOS wheels"
      os: osx
      language: shell
      env: CC=gcc CXX=g++ MACOSX_DEPLOYMENT_TARGET=10.14
      osx_image: xcode10.2
      install: python3 -m pip install cibuildwheel==1.3.0
      script: python3 -m cibuildwheel --output-dir wheelhouse
      after_success: bash -x -e .travis/after_success.sh

env:
  global:
    - CIBW_BUILD_VERBOSITY: 3
    - CIBW_SKIP: cp27-*
    - CIBW_SKIP: cp34-*
    - CIBW_SKIP: cp35-*
    - CIBW_BUILD: cp3?-*
    - CIBW_REPAIR_WHEEL_COMMAND_MACOS='delocate-listdeps {wheel} && delocate-wheel -v -w {dest_dir} {wheel}'
    - CIBW_BEFORE_BUILD_LINUX='yum install -y centos-release-scl && yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++ clang cmake ninja-build freeglut freeglut-devel libX11-devel mesa-libGLU-devel byacc'
    - CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

addons:
  apt:
    packages:
      - libgl1-mesa-dev

  homebrew:
    update: true
    packages:
    - cmake
    - ninja

branches:
  only:
    - master

stages:
#  - test
  - name: deploy
    if: repo = fbertola/bgfx-python
#    if: tag =~ ^v\d+\.\d+\.\d+$ AND repo = fbertola/bgfx-python

notifications:
  email: false