languages:
  - cpp
  - python

git:
  submodules: true

matrix:
  include:
    - compiler: gcc
      os: linux
      python: 3.7
    - compiler: clang
      os: osx
      python: 3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang
    - cmake
    - ninja

script:
  - python setup.py sdist bdist_wheel

#branches:
#  only:
#    - master

osx_image: xcode9.3
dist: xenial