languages:
  - cpp
  - python

sudo: false

python:
  - 3.7

git:
  quiet: true
  depth: false
  submodules: true

env:
  global:
    - LANG: en_US.UTF-8


matrix:
  include:
    - compiler: gcc
      os: linux
      env: CC=gcc-8 CXX=g++-8
      python: 3.6-dev
    - compiler: clang
      os: osx
      env: CC=gcc CXX=g++
      python: 3.6-dev

addons:
  homebrew:
    update: true
    packages:
    - cmake
    - python@3
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang
    - cmake
    - ninja
    - mesa-common-dev

before_install:
  - pyenv global 3.7

install:
  - pip install --user -U pip setuptools wheel
  - pip install --user scikit-build cmake ninja

script:
  - python setup.py sdist bdist_wheel

#branches:
#  only:
#    - master

osx_image: xcode10.2
dist: xenial