languages:
  - cpp
  - python

sudo: false

git:
  quiet: true
  depth: false
  submodules: true

env:
  global:
    - LANG: en_US.UTF-8


matrix:
  include:

    - name: "Python 3.7.1 on Xenial Linux"
      compiler: gcc
      os: linux
      python: 3.7
      dist: xenial
      env: CC=gcc-8 CXX=g++-8
      before_install: pyenv global 3.7

    - name: "Python 3.7.2 on macOS"
      compiler: clang
      os: osx
      env: CC=gcc CXX=g++
      osx_image: xcode10.2
      language: cpp
      before_install: python3 --version ; pip3 --version ; sw_vers

addons:
  homebrew:
    update: true
    packages:
    - cmake
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang
    - cmake
    - ninja
    - mesa-common-dev

install:
  - pip3 install --user -U pip setuptools wheel
  - pip3 install --user scikit-build cmake ninja

script:
  - python3 setup.py sdist bdist_wheel

#branches:
#  only:
#    - master

notifications:
  email: false