languages:
  - cpp
  - python

sudo: true

git:
  depth: false
  submodules: true

matrix:
  include:
    - compiler: gcc
      os: linux
      python: 3.7
    - compiler: clang
      os: osx
      python: 3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang
    - cmake
    - ninja

install:
  - pip install --user -U pip setuptools wheel
  - pip install --user scikit-build cmake ninja

script:
  - python setup.py sdist bdist_wheel

#branches:
#  only:
#    - master

osx_image: xcode9.3
dist: xenial