name: build

on: [push]

jobs:
  build_wheels:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel scikit-build cmake ninja loguru cibuildwheel==1.5.2

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          - CIBW_BUILD_VERBOSITY=0
          - CIBW_SKIP="*-manylinux_i686"
          - CIBW_BUILD="cp36-* cp37-* cp38-*"
          - CIBW_REPAIR_WHEEL_COMMAND_MACOS="delocate-listdeps {wheel} && delocate-wheel -v -w {dest_dir} {wheel}"
          - CIBW_BEFORE_BUILD_LINUX="yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++ clang freeglut freeglut-devel libX11-devel mesa-libGLU-devel byacc"
          - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014

  build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          name: Install Python
          with:
            python-version: '3.7'

        - name: Build sdist
          run: python setup.py sdist

#        - uses: actions/upload-artifact@v2
#          with:
#            path: dist/*.tar.gz