name: build

on: [push]

jobs:
  build_wheels:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel scikit-build cmake ninja loguru cibuildwheel==1.7.2 cppyy clang

      - name: Build wheels
        shell: bash
        run: |
          if [[ ! -e /usr/include ]]; then
              export SDKROOT="$(xcrun --show-sdk-path)"
          fi
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 0
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_BUILD: "cp36-* cp37-* cp38-*"
          CIBW_BEFORE_BUILD_MACOS: "pip install --upgrade delocate"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && delocate-wheel -v -w {dest_dir} {wheel}"
          CIBW_BEFORE_BUILD_LINUX: |
            pip install clang==3.4 && \
            yum install -y clang libstdc++ freeglut freeglut-devel libX11-devel mesa-libGLU-devel byacc
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/fbertola/manylinux2014_gcc

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          name: Install Python
          with:
            python-version: "3.7"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel scikit-build cmake ninja loguru

        - name: Build sdist
          run: python setup.py sdist

        - uses: actions/upload-artifact@v2
          with:
            path: dist/*.tar.gz