name: tests

on: [push]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libosmesa6-dev -y

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox

      - name: Run tests
        run: |
          rm -rf bgfx
          /usr/bin/xvfb-run --auto-servernum nox -rs tests -- tests